export const FORM_FIELDS = {
  EMAIL: "email",
  EMAIL_ERROR: "error_email",
  PASSWORD: "password",
  PASSWORD_ERROR: "error_password",
  REPEAT_PASSWORD: "repeat_password",
  REPEAT_PASSWORD_ERROR: "error_repeat_password",
  USERNAME: "username",
  USERNAME_ERROR: "error_username",
  FIRSTNAME: "firstname",
  FIRSTNAME_ERROR: "error_firstname",
  LASTNAME: "lastname",
  LASTNAME_ERROR: "error_lastname",
  GENERAL_ERROR: "error_general",
} as const;
